version: 0.2

phases:
  install:
    commands:
      - echo Installing Helm...
      - curl -sSL https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
      - echo Installing yq...
      - curl -L https://github.com/mikefarah/yq/releases/download/v4.9.8/yq_linux_amd64 -o /usr/bin/yq
      - chmod +x /usr/bin/yq

  pre_build:
    commands:
      - echo Starting Docker daemon...
      - nohup /usr/local/bin/dockerd > /dev/null 2>&1 &
      - timeout 15 sh -c "until docker info; do echo 'Waiting for Docker to start...'; sleep 1; done"
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_URL
      - echo Configuring Git for GitHub...
      - git config --global credential.helper store
      - echo "${GITHUB_USERNAME}:${GITHUB_TOKEN}" > ~/.git-credentials
      - echo Cloning HelmChart repository from GitHub...
      - git clone https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/SK-Rookies-Final3/HelmChart-for-Argo.git

  build:
    commands:
      - echo "Generating unique IMAGE_TAG based on timestamp..."
      - export IMAGE_TAG=$(date +%Y%m%d%H%M%S)
      - echo Building the backend JAR...
      - ./gradlew clean bootJar --exclude-task test
      - echo Building the Docker image...
      - docker build -t $ECR_REPO:$IMAGE_TAG .
      - docker tag $ECR_REPO:$IMAGE_TAG $ECR_URL/$ECR_REPO:$IMAGE_TAG

  post_build:
    commands:
      - echo Build completed on date
      - echo Pushing Docker image to ECR with tag $IMAGE_TAG...
      - docker push $ECR_URL/$ECR_REPO:$IMAGE_TAG
      - echo Updating backend image tag in values.yaml...
      - yq eval '.backend.image.tag = "'$IMAGE_TAG'"' -i HelmChart-for-Argo/helm-charts/values.yaml
      - yq eval '.backendTimestamp = "'$(date +%Y%m%d%H%M%S)'"' -i HelmChart-for-Argo/helm-charts/values.yaml
      - echo Packaging Helm chart...
      - cd HelmChart-for-Argo
      - helm package ./helm-charts -d output
      - echo Generating Helm repository index...
      - helm repo index output --url http://argocd-helm-repo.s3-website.ap-northeast-2.amazonaws.com
      - echo Uploading Helm chart and index to S3...
      - aws s3 cp output/ s3://argocd-helm-repo/ --recursive
      - echo Committing changes to values.yaml...
      - git config --global user.name "CodeBuild"
      - git config --global user.email "codebuild@example.com"
      - git add ./helm-charts/values.yaml
      - git commit -m "Update backendTimestamp to $IMAGE_TAG" || echo "No changes to commit"
      - git push origin main || echo "No changes to push"

artifacts:
  files:
    - '**/*'
  discard-paths: yes
