version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies...
      - npm install
      - echo Installing missing Babel dependency...
      - npm install @babel/plugin-proposal-private-property-in-object --save-dev
      - echo Installing Helm...
      - curl -sSL https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

  pre_build:
    commands:
      - echo Starting Docker daemon...
      - nohup /usr/local/bin/dockerd > /dev/null 2>&1 &
      - timeout 15 sh -c "until docker info; do echo 'Waiting for Docker to start...'; sleep 1; done"
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_URL
      - echo Configuring Git for GitHub...
      - git config --global credential.helper store
      - echo "${GITHUB_USERNAME}:${GITHUB_TOKEN}" > ~/.git-credentials
      - echo Cloning HelmChart repository from GitHub...
      - git clone https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/SK-Rookies-Final3/HelmChart-for-Argo.git

  build:
    commands:
      - echo Building the React project...
      - npm run build
      - echo Building the Docker image...
      - docker build -t $ECR_REPO:latest .
      - docker tag $ECR_REPO:latest $ECR_URL/$ECR_REPO:latest

  post_build:
    commands:
      - echo Build completed on date
      - echo Pushing the Docker image...
      - docker push $ECR_URL/$ECR_REPO:latest
      - echo Updating frontendTimestamp in values.yaml...
      - sed -i "s/frontendTimestamp:.*/frontendTimestamp:\"$(date +%Y%m%d%H%M%S)\"/" HelmChart-for-Argo/helm-charts/values.yaml
      - echo Packaging Helm chart...
      - helm package ./helm-charts -d output
      - echo Generating Helm repository index...
      - helm repo index output --url https://$S3_BUCKET.s3.$AWS_REGION.amazonaws.com/path/to/charts
      - echo Uploading Helm chart and index to S3...
      - aws s3 cp output/ s3://$S3_BUCKET/path/to/charts --recursive --acl public-read
      - echo Committing changes to values.yaml...
      - git config --global user.name "CodeBuild"
      - git config --global user.email "codebuild@example.com"
      - git add helm-charts/values.yaml
      - git commit -m "Update frontendTimestamp to $(date +%Y%m%d%H%M%S)" || echo "No changes to commit"
      - git push origin main || echo "No changes to push"

artifacts:
  files:
    - '**/*'
  discard-paths: yes
