version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies...
      - npm install

  pre_build:
    commands:
      - echo Starting Docker daemon...
      - nohup /usr/local/bin/dockerd > /dev/null 2>&1 &
      - timeout 15 sh -c "until docker info; do echo 'Waiting for Docker to start...'; sleep 1; done"
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 565393064007.dkr.ecr.ap-northeast-2.amazonaws.com

  build:
    commands:
      - echo Building the React project...
      - npm run build
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t frontend-ecr:latest .
      - docker tag frontend-ecr:latest 565393064007.dkr.ecr.ap-northeast-2.amazonaws.com/frontend-ecr:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 565393064007.dkr.ecr.ap-northeast-2.amazonaws.com/frontend-ecr:latest

artifacts:
  files:
    - '**/*'
  discard-paths: yes
